### ISSUE TITLE
Aborted Created dump - REST

### ISSUE THREAD

**Issue by koenieee** [pdumais/DumaisLib#2]
Hi,

I think I found a bug in your code. When the RestEngine is destructed, it also destructs the callback function. 
After the engine is destructed I get the message: Aborted memory dump created.
I think the problem exists in RESTCallback destructor. I am not sure if it's correct to also destroy the  std::function<void(RESTContext*)> mCallback; 
The best would be to let the user destroy his own callback function.

I don't have a solution at the moment for the problem, so for now I will just comment the section where you destroy the callback function.

If you want to look at my implementation of your REST library, you can find it here: 
https://github.com/HU-R2D2/communication-protocols/tree/develop.restAPI

Look into the test folder to find the gtest.

Anyway, thank you very much for your hard work on REST and JSON library!

Kind regards,

Koen van der Kruk

**Comment by koenieee** [comment]
Hmm, it's also possible I am using the wrong version of gcc. http://stackoverflow.com/questions/19170166/delete-pointer-to-stdfunction

I use Cmake in combination with Cygwin to compile the REST project.

**Comment by pdumais** [comment]
Thank you. I'll have alook

**Comment by pdumais** [comment]
I cannot reproduce this. Do you get the crash simply by creating a callback and then deleting the RESTEngine?

The RESTCallback's destructor is empty. The std::function creation/destruction is implicit in the RESTCallback.

**Comment by koenieee** [comment]
Yes the exact example you provided for REST, when the program is finished the last message is 'Aborted memory dump created'

**Comment by pdumais** [comment]
The example on www.dumaisnet.ca? That example is a bit outdated, I should update it.

if I run rest.out from the test folder everything is good. I'm using gcc 4.9.2 on slackware 14.1 64.
Can you confirm that the test application works?

I'll rework the example on my site

**Comment by koenieee** [comment]
I am compiling under cygwin, with gcc v5x I used your example: http://www.dumaisnet.ca/index.php?article=c3db6d72f1dd661d22f36ea2f76da041

**Comment by pdumais** [comment]
That example just doesn't work because it is outdated. You surely had to modify the code to make it work. Can run the test from the "Test" folder and tell me if you get the same result?

**Comment by pdumais** [comment]
I have just updated gcc to 5.3.0 and tried the test and it does work properly.
